# Import

In [1]:
import numpy as np

# # Create arrays

In [4]:
a = np.array([10,12,31,9])
# a = np.array([10, 11.2, 2])
# a = np.array([10, 11.2, 2, "Hello"])
print(a)
print(type(a))
print(a.dtype)
print(type(a[0]))
print("Shape of a", a.shape, "This gives us the number of elements per dimension")
print("Num. of dimesnions", a.ndim)
print("Total number of elements in the array", a.size)

[10 12 31  9]
<class 'numpy.ndarray'>
int64
<class 'numpy.int64'>
Shape of a (4,) This gives us the number of elements per dimension
Num. of dimesnions 1
Total number of elements in the array 4


In [6]:
b = np.array([[1, 2], [3, 4]])   # 2D
print(b)
print(type(b))
print(b.dtype)
print(type(b[0]))
print("Shape of b", b.shape, "This gives us the number of elements per dimension")
print("Num. of dimesnions", b.ndim)
print("Total number of elements in the array", b.size)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
int64
<class 'numpy.ndarray'>
Shape of b (2, 2) This gives us the number of elements per dimension
Num. of dimesnions 2
Total number of elements in the array 4


# Vectorization — no loops needed

In [9]:
a = np.array([10,12,31,9])
b = np.ones_like(a)
print("a", a)
print("b", b)
print(a+b)

a [10 12 31  9]
b [1 1 1 1]
[11 13 32 10]


# Broadcasting


In [ ]:
a = np.array([10,12,31,9])

In [7]:
a * 2

array([20, 24, 62, 18])

# Boolean Indexing

In [10]:
a = np.array([10,12,31,9])
x = [True, False, True, False]
a[x]

array([10, 31])

In [12]:
mask = a > 5
mask

array([ True,  True,  True,  True])

In [13]:
a[mask]

array([10, 12, 31,  9])

# Useful functions

In [14]:
a = np.array([1, 2, 3, 4, 5])


print(a.mean())       # 3.0
print(a.sum())        # 15
print(a.reshape(1,5)) # [[1 2 3 4 5]]
print(np.zeros((3,3)))# 3x3 matrix of zeros

3.0
15
[[1 2 3 4 5]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
